83 part2 engine hints (#91)
* Adopt conventional naming for  modules, using _ underscore between words

* Add test_connect_to_mongo()

* Bugfix: avoid trying to convert y-m-d to an integer

* Bugfix: avoid changing the sparsity structure of a csr_matrix, as it is expensive

* Add tqdm progress bar

* Add etl_mongo_movie_titles

* Bugfix: deal with the admonition to Call MongoClient.close() to safely shut down your client and free up resources

* Index rating by user_id

* Speed up bulk INSERT using .import

* Add _run_sqlite_child helper

* Introduce an _enabled boolean, so test runs in CI won't try to connect to non-existant Mongo database

* Only use .engine if we've defined it

* Add a script: pipenv run unittest

* Prefer to use an uncompressed rating.csv file, to accommodate sqlite .import

* Remove the gzip child process, as it is no longer needed

* Move etl_mongo_movie_titles to separate module

* Add etl_helpers

* Nothing wrong with that FK, no slow-down, so restore it as it was

* Add test_get_movie_title

* Bugfix: mutate netflix_ids return value, rather than titles. Also, add test_titles_to_ids

* Add test_ids_to_titles

* Add (bogus) test_get_recommendations

* Add test for get_data(), which is gratuitously hard to invoke

* Add test_display_recommendations

* Add test_create_user_matrix, such as it is

* Add test_recommend

* Delete the etl_helpers module and improve the coverage config (responding to a review remark)

* Mark that etl_mongo_movie_titles is not expected to execute on every interactive test run

* Make progress report a bit less chatty

* Zero a matrix entry rather than delete it

* Take care to close() connection

* Make etl_mongo_movie_titles idempotent. Since the existing implementation imposed no PK, each execution would keep adding dups

* Annotate get_movie_{id,title}

* Annotate titles_to_ids, ids_to_titles

* Annotate get_recommendations

* Annotate display_recommendations

* Annotate create_user_matrix

* Unit tests fail with:  AttributeError: 'coo_matrix' object has no attribute 'predict'

* .close() the mongo connection

* engine_etl now calls read_netflix_txt(), as was intended before a recent merge conflict

* Change the recommendation engine so it relies on a cached LIGHTFM_MODEL_PKL file

* It turns out it's important to import that noisey LightFM _before_ giving pickle.load() a chance to do it for us

* Return a set() of recommendations, rather than an order list

* It turns out we have no index on title, so avoid a double find() call

* Ignore emacs ~ "backup" files

* test_get_recommendations() isn't helpful, so elide it

* test_get_recommendations() isn't helpful, so elide it

* No need for .recommend() to default the user ID

* Annotate get_movie_id()

* Annotate get_movie_title()

* Annotate {titles_to_ids, ids_to_titles}

* Annotate get_recommendations()

* Delete a troublesome side effect call to display_recommendations(recommendations), which static analysis reveals uses the wrong type

* Prefer to use a warnings context manager

* Simplify an import

* Simplify an import

* Focus on first user_id

* Ensure we never get NameError for unbound "total_length"

* Verify that df.year exists

* Clarify that we're returning a class type

* Delete a debug print()